"""Database seeder for CarbonIQ: creates 30 realistic carbon projects with credits, scores, and risk signals."""
from __future__ import annotations

import sys
from datetime import date, datetime, timezone
from decimal import Decimal
from pathlib import Path
from uuid import uuid4

# Ensure services/api is in Python path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "services" / "api"))

from app.database.session import SessionLocal
from app.models.credit import CarbonCredit
from app.models.enums import ProjectCategory, ProjectStatus, RiskSeverity, VerificationStatus
from app.models.project import Project
from app.models.score import ProjectScore, RiskSignal

PROJECT_DATA = [
    {
        "name": "Sundarbans Mangrove Climate Resilience",
        "developer": "Bengal Delta Conservation Alliance",
        "type": "Mangrove Restoration",
        "category": ProjectCategory.REMOVAL,
        "country": "IN",
        "region": "West Bengal",
        "registry": "Verra",
        "registry_id": "VCS-2341",
        "methodology": "VM0033 Tidal Wetland Restoration",
        "vintage": 2024,
        "price": Decimal("1450.00"),
        "currency": "INR",
        "quantity": Decimal("65000.000"),
        "sdgs": [13, 14, 15, 8],
        "score": Decimal("88.5"),
        "risk": Decimal("14.0"),
        "confidence": Decimal("0.92"),
        "description": "High-permanence mangrove reforestation and community cyclone buffer protection across the lower Sundarbans estuary.",
    },
    {
        "name": "Araku Valley Agroforestry & Biochar",
        "developer": "Eastern Ghats Tribal Trust",
        "type": "Biochar & Agroforestry",
        "category": ProjectCategory.REMOVAL,
        "country": "IN",
        "region": "Andhra Pradesh",
        "registry": "Gold Standard",
        "registry_id": "GS-8912",
        "methodology": "GS TPD Agroforestry & Pyrogenic Carbon",
        "vintage": 2024,
        "price": Decimal("1750.00"),
        "currency": "INR",
        "quantity": Decimal("42000.000"),
        "sdgs": [1, 2, 13, 15],
        "score": Decimal("91.0"),
        "risk": Decimal("11.5"),
        "confidence": Decimal("0.95"),
        "description": "Indigenous coffee farmers sequester carbon through shade-tree planting and high-temperature mobile biochar kilns.",
    },
    {
        "name": "Thar Desert Clean Wind Initiative",
        "developer": "Rajasthan Clean Power Ltd",
        "type": "Grid-Connected Wind",
        "category": ProjectCategory.REDUCTION,
        "country": "IN",
        "region": "Rajasthan",
        "registry": "Verra",
        "registry_id": "VCS-1104",
        "methodology": "ACM0002 Grid-connected Electricity from Renewables",
        "vintage": 2023,
        "price": Decimal("680.00"),
        "currency": "INR",
        "quantity": Decimal("180000.000"),
        "sdgs": [7, 8, 13],
        "score": Decimal("74.0"),
        "risk": Decimal("22.0"),
        "confidence": Decimal("0.88"),
        "description": "150 MW utility-scale wind farm displacing fossil generation on the northern regional power grid.",
    },
    {
        "name": "Jari Pará Amazon Forest Conservation",
        "developer": "Biofílica Ambipar",
        "type": "REDD+ Avoided Deforestation",
        "category": ProjectCategory.AVOIDANCE,
        "country": "BR",
        "region": "Pará",
        "registry": "Verra",
        "registry_id": "VCS-1115",
        "methodology": "VM0015 Avoided Unplanned Deforestation",
        "vintage": 2023,
        "price": Decimal("1250.00"),
        "currency": "INR",
        "quantity": Decimal("95000.000"),
        "sdgs": [13, 15, 6],
        "score": Decimal("81.5"),
        "risk": Decimal("28.0"),
        "confidence": Decimal("0.84"),
        "description": "Protecting 496,000 hectares of primary Amazon rainforest from expanding agricultural and logging frontiers.",
    },
    {
        "name": "Rift Valley Clean Cookstoves Project",
        "developer": "Burn Manufacturing Kenya",
        "type": "Clean Cookstoves",
        "category": ProjectCategory.REDUCTION,
        "country": "KE",
        "region": "Nakuru",
        "registry": "Gold Standard",
        "registry_id": "GS-4420",
        "methodology": "TPDDTEC Improved Cookstoves",
        "vintage": 2024,
        "price": Decimal("920.00"),
        "currency": "INR",
        "quantity": Decimal("110000.000"),
        "sdgs": [3, 5, 7, 13],
        "score": Decimal("84.0"),
        "risk": Decimal("16.0"),
        "confidence": Decimal("0.90"),
        "description": "Distribution of fuel-efficient biomass cookstoves reducing indoor air pollution and wood consumption across 120,000 households.",
    },
    {
        "name": "Sumatra Peatland Rewetting & Preservation",
        "developer": "Rimbaraya Ecological Corp",
        "type": "Peatland Restoration",
        "category": ProjectCategory.REMOVAL,
        "country": "ID",
        "region": "Central Kalimantan",
        "registry": "Verra",
        "registry_id": "VCS-1378",
        "methodology": "VM0007 REDD+ Tropical Peatlands",
        "vintage": 2024,
        "price": Decimal("1600.00"),
        "currency": "INR",
        "quantity": Decimal("75000.000"),
        "sdgs": [13, 14, 15],
        "score": Decimal("86.5"),
        "risk": Decimal("19.0"),
        "confidence": Decimal("0.89"),
        "description": "Hydrological canal blocking and rewetting of vulnerable tropical peat swamp forests protecting endangered orangutan habitats.",
    },
    {
        "name": "Appalachian Forest Carbon Recovery",
        "developer": "Eastern Woodlands Trust",
        "type": "Improved Forest Management",
        "category": ProjectCategory.REMOVAL,
        "country": "US",
        "region": "West Virginia",
        "registry": "American Carbon Registry",
        "registry_id": "ACR-523",
        "methodology": "ACR IFM Non-Federal US Forests",
        "vintage": 2024,
        "price": Decimal("2400.00"),
        "currency": "INR",
        "quantity": Decimal("35000.000"),
        "sdgs": [13, 15],
        "score": Decimal("89.0"),
        "risk": Decimal("12.0"),
        "confidence": Decimal("0.94"),
        "description": "Long-term conservation harvest deferral and mature hardwood stand carbon stock accumulation across 40,000 acres.",
    },
    {
        "name": "Gujarat Biogas & Methane Capture",
        "developer": "Surat Renewable Energy Solutions",
        "type": "Agricultural Methane Capture",
        "category": ProjectCategory.REDUCTION,
        "country": "IN",
        "region": "Gujarat",
        "registry": "Gold Standard",
        "registry_id": "GS-6619",
        "methodology": "AMS-III.D Methane Recovery in Animal Manure",
        "vintage": 2023,
        "price": Decimal("790.00"),
        "currency": "INR",
        "quantity": Decimal("58000.000"),
        "sdgs": [6, 7, 12, 13],
        "score": Decimal("79.5"),
        "risk": Decimal("18.0"),
        "confidence": Decimal("0.87"),
        "description": "Anaerobic dairy farm digestors converting bovine waste into pipeline-grade biogas and organic compost fertilizer.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Western Ghats Ecological Afforestation",
        "developer": "Sahyadri Bio-Diversity Council",
        "type": "Reforestation",
        "category": ProjectCategory.REMOVAL,
        "country": "IN",
        "region": "Karnataka",
        "registry": "Verra",
        "registry_id": "VCS-3012",
        "methodology": "AR-ACM0003 Afforestation on Degraded Lands",
        "vintage": 2024,
        "price": Decimal("1380.00"),
        "currency": "INR",
        "quantity": Decimal("85000.000"),
        "sdgs": [13, 15, 6],
        "score": Decimal("87.0"),
        "risk": Decimal("15.5"),
        "confidence": Decimal("0.91"),
        "description": "Restoring endemic tropical evergreen species across critical elephant and tiger wildlife corridors.",
        "image_url": "https://images.unsplash.com/photo-1631006995557-9866a74ee05c?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Tamil Nadu Wind Energy Collective",
        "developer": "Muppandal Renewable Power",
        "type": "Wind energy",
        "category": ProjectCategory.REDUCTION,
        "country": "IN",
        "region": "Tamil Nadu",
        "registry": "Gold Standard",
        "registry_id": "GS-5108",
        "methodology": "ACM0002 Grid Connected Renewables",
        "vintage": 2023,
        "price": Decimal("640.00"),
        "currency": "INR",
        "quantity": Decimal("210000.000"),
        "sdgs": [7, 8, 13],
        "score": Decimal("77.0"),
        "risk": Decimal("20.0"),
        "confidence": Decimal("0.89"),
        "description": "High-capacity wind turbines harnessing mountain pass winds to displace coal base-load electricity.",
        "image_url": "https://images.unsplash.com/photo-1543419163-155ebaf80730?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Casanare Savanna Afforestation & Soil Carbon",
        "developer": "Llanos Green Assets SA",
        "type": "Reforestation",
        "category": ProjectCategory.REMOVAL,
        "country": "CO",
        "region": "Casanare",
        "registry": "Verra",
        "registry_id": "VCS-2890",
        "methodology": "VM0042 Improved Agricultural Land Management",
        "vintage": 2024,
        "price": Decimal("1550.00"),
        "currency": "INR",
        "quantity": Decimal("60000.000"),
        "sdgs": [13, 15, 8],
        "score": Decimal("86.0"),
        "risk": Decimal("16.0"),
        "confidence": Decimal("0.90"),
        "description": "Establishing mixed native timber and deep-root pasture systems across savanna grazing lands.",
        "image_url": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Mekong Delta Coastal Mangrove Buffer",
        "developer": "Vietnam Climate Action Network",
        "type": "Mangrove Restoration",
        "category": ProjectCategory.REMOVAL,
        "country": "VN",
        "region": "Ca Mau",
        "registry": "Verra",
        "registry_id": "VCS-2675",
        "methodology": "VM0033 Tidal Wetland Restoration",
        "vintage": 2024,
        "price": Decimal("1650.00"),
        "currency": "INR",
        "quantity": Decimal("52000.000"),
        "sdgs": [13, 14, 15, 1],
        "score": Decimal("89.5"),
        "risk": Decimal("13.0"),
        "confidence": Decimal("0.93"),
        "description": "Protecting smallholder shrimp farms with dense seaward Rhizophora mangrove barriers against typhoon surges.",
        "image_url": "https://images.unsplash.com/photo-1718661934073-ecfd78710651?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Pacific Northwest Soil Biochar Sequestration",
        "developer": "Cascade Biochar Systems LLC",
        "type": "Biochar",
        "category": ProjectCategory.REMOVAL,
        "country": "US",
        "region": "Oregon",
        "registry": "American Carbon Registry",
        "registry_id": "ACR-782",
        "methodology": "ACR Methodology for Biochar Carbon Sequestration",
        "vintage": 2024,
        "price": Decimal("2250.00"),
        "currency": "INR",
        "quantity": Decimal("28000.000"),
        "sdgs": [12, 13, 15],
        "score": Decimal("92.0"),
        "risk": Decimal("9.5"),
        "confidence": Decimal("0.96"),
        "description": "Pyrolysis of certified forestry residue into recalcitrant black carbon for agricultural soil amendment.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Cerrado Native Vegetation Re-establishment",
        "developer": "Instituto Bioma Brasil",
        "type": "Reforestation",
        "category": ProjectCategory.MIXED,
        "country": "BR",
        "region": "Goiás",
        "registry": "Verra",
        "registry_id": "VCS-2441",
        "methodology": "VM0015 Landscape Restoration",
        "vintage": 2023,
        "price": Decimal("1180.00"),
        "currency": "INR",
        "quantity": Decimal("80000.000"),
        "sdgs": [6, 13, 15],
        "score": Decimal("83.0"),
        "risk": Decimal("19.0"),
        "confidence": Decimal("0.88"),
        "description": "Revitalizing savanna headwaters and deep taproot woody vegetation in agricultural transition zones.",
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Nyungwe Buffer Zone Clean Cooking",
        "developer": "Rwanda Clean Energy Cooperative",
        "type": "Clean Cookstoves",
        "category": ProjectCategory.REDUCTION,
        "country": "RW",
        "region": "Southern Province",
        "registry": "Gold Standard",
        "registry_id": "GS-3882",
        "methodology": "TPDDTEC Improved Cookstoves",
        "vintage": 2024,
        "price": Decimal("880.00"),
        "currency": "INR",
        "quantity": Decimal("64000.000"),
        "sdgs": [3, 5, 13, 15],
        "score": Decimal("85.0"),
        "risk": Decimal("15.0"),
        "confidence": Decimal("0.91"),
        "description": "Eliminating firewood extraction inside national park boundaries through insulated institutional stoves.",
        "image_url": "https://images.unsplash.com/photo-1544717305-2782549b5136?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Outback Soil Carbon Regeneration",
        "developer": "Queensland Rangeland Alliance",
        "type": "Improved Agricultural Land Management",
        "category": ProjectCategory.REMOVAL,
        "country": "AU",
        "region": "Queensland",
        "registry": "Verra",
        "registry_id": "VCS-3180",
        "methodology": "VM0042 Soil Organic Carbon",
        "vintage": 2023,
        "price": Decimal("1920.00"),
        "currency": "INR",
        "quantity": Decimal("44000.000"),
        "sdgs": [13, 15, 2],
        "score": Decimal("88.0"),
        "risk": Decimal("14.0"),
        "confidence": Decimal("0.92"),
        "description": "Rotational high-density planned grazing enhancing perennial root depth and soil organic matter.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Maya Biosphere Reserve Conservation",
        "developer": "Asociación Forestal de Petén",
        "type": "REDD+ Avoided Deforestation",
        "category": ProjectCategory.AVOIDANCE,
        "country": "MX",
        "region": "Yucatan Border",
        "registry": "Verra",
        "registry_id": "VCS-1994",
        "methodology": "VM0015 Avoided Unplanned Deforestation",
        "vintage": 2023,
        "price": Decimal("1120.00"),
        "currency": "INR",
        "quantity": Decimal("115000.000"),
        "sdgs": [1, 8, 13, 15],
        "score": Decimal("82.5"),
        "risk": Decimal("24.0"),
        "confidence": Decimal("0.86"),
        "description": "Community forest concessions sustainably harvesting non-timber products while preventing illegal cattle clearing.",
        "image_url": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Kenya Great Rift Mobile Biochar Units",
        "developer": "Rift Agro-Carbon Ltd",
        "type": "Biochar",
        "category": ProjectCategory.REMOVAL,
        "country": "KE",
        "region": "Rift Valley",
        "registry": "Gold Standard",
        "registry_id": "GS-7721",
        "methodology": "GS Methodology for Pyrogenic Biochar",
        "vintage": 2024,
        "price": Decimal("1850.00"),
        "currency": "INR",
        "quantity": Decimal("38000.000"),
        "sdgs": [1, 2, 13, 15],
        "score": Decimal("90.5"),
        "risk": Decimal("12.0"),
        "confidence": Decimal("0.94"),
        "description": "Transforming invasive prosopis juliflora shrub thickets into high-grade agricultural biochar pellets.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Karnataka Shade-Grown Agroforestry",
        "developer": "Malnad Sustainable Planters Union",
        "type": "Biochar & Agroforestry",
        "category": ProjectCategory.REMOVAL,
        "country": "IN",
        "region": "Karnataka",
        "registry": "Gold Standard",
        "registry_id": "GS-8114",
        "methodology": "GS TPD Agroforestry & Pyrogenic Carbon",
        "vintage": 2024,
        "price": Decimal("1720.00"),
        "currency": "INR",
        "quantity": Decimal("46000.000"),
        "sdgs": [2, 8, 13, 15],
        "score": Decimal("90.0"),
        "risk": Decimal("12.5"),
        "confidence": Decimal("0.93"),
        "description": "Multi-tier native canopy intercropping with cardamom and pepper for permanent carbon capture.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Kalimantan Deep Peat Rewetting Corridor",
        "developer": "Borneo Peat Ecosystems",
        "type": "Peatland Restoration",
        "category": ProjectCategory.REMOVAL,
        "country": "ID",
        "region": "West Kalimantan",
        "registry": "Verra",
        "registry_id": "VCS-2710",
        "methodology": "VM0007 Peatland Rewetting",
        "vintage": 2024,
        "price": Decimal("1680.00"),
        "currency": "INR",
        "quantity": Decimal("62000.000"),
        "sdgs": [13, 14, 15],
        "score": Decimal("87.5"),
        "risk": Decimal("17.0"),
        "confidence": Decimal("0.90"),
        "description": "Damming drainage canals across 35,000 hectares of degraded peatlands to halt underground combustion.",
        "image_url": "https://images.unsplash.com/photo-1718661934073-ecfd78710651?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Southern Rockies Wildfire Recovery Reforestation",
        "developer": "Colorado Forest Health Project",
        "type": "Reforestation",
        "category": ProjectCategory.REMOVAL,
        "country": "US",
        "region": "Colorado",
        "registry": "American Carbon Registry",
        "registry_id": "ACR-640",
        "methodology": "ACR Reforestation of Degraded Lands",
        "vintage": 2024,
        "price": Decimal("2350.00"),
        "currency": "INR",
        "quantity": Decimal("31000.000"),
        "sdgs": [13, 15],
        "score": Decimal("88.5"),
        "risk": Decimal("14.5"),
        "confidence": Decimal("0.93"),
        "description": "Post-megafire replanting of ponderosa pine and Douglas fir across high-severity burn scars.",
        "image_url": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Mata Atlântica Biodiversity Wildlife Corridors",
        "developer": "Regua Conservation Trust",
        "type": "Reforestation",
        "category": ProjectCategory.REMOVAL,
        "country": "BR",
        "region": "Rio de Janeiro",
        "registry": "Verra",
        "registry_id": "VCS-2198",
        "methodology": "AR-ACM0003 Native Forest Restoration",
        "vintage": 2024,
        "price": Decimal("1420.00"),
        "currency": "INR",
        "quantity": Decimal("54000.000"),
        "sdgs": [6, 13, 15],
        "score": Decimal("89.0"),
        "risk": Decimal("13.5"),
        "confidence": Decimal("0.92"),
        "description": "Connecting fragmented Atlantic rainforest reserves to protect endemic birds and primates.",
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Lake Victoria Riparian Wetland Buffer",
        "developer": "Kisumu Ecological Network",
        "type": "Mangrove Restoration",
        "category": ProjectCategory.REMOVAL,
        "country": "KE",
        "region": "Kisumu",
        "registry": "Gold Standard",
        "registry_id": "GS-4903",
        "methodology": "GS Wetlands Restoration",
        "vintage": 2024,
        "price": Decimal("1280.00"),
        "currency": "INR",
        "quantity": Decimal("48000.000"),
        "sdgs": [6, 13, 14, 15],
        "score": Decimal("86.5"),
        "risk": Decimal("16.0"),
        "confidence": Decimal("0.89"),
        "description": "Papyrus and coastal macrophyte belt restoration preventing agricultural nutrient runoff into Lake Victoria.",
        "image_url": "https://images.unsplash.com/photo-1718661934073-ecfd78710651?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Rajasthan Decentralized Solar Microgrid",
        "developer": "Marwar Clean Power Pvt Ltd",
        "type": "Grid-Connected Wind",
        "category": ProjectCategory.REDUCTION,
        "country": "IN",
        "region": "Rajasthan",
        "registry": "Gold Standard",
        "registry_id": "GS-6290",
        "methodology": "AMS-I.D Grid Connected Renewable Electricity",
        "vintage": 2023,
        "price": Decimal("620.00"),
        "currency": "INR",
        "quantity": Decimal("140000.000"),
        "sdgs": [7, 8, 9, 13],
        "score": Decimal("78.0"),
        "risk": Decimal("19.5"),
        "confidence": Decimal("0.90"),
        "description": "Replacing diesel pumps and generators with 80 MW community solar arrays across 45 villages.",
        "image_url": "https://images.unsplash.com/photo-1543419163-155ebaf80730?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Madre de Dios Brazil Nut Concession Protection",
        "developer": "Federación de Castañeros de Madre de Dios",
        "type": "REDD+ Avoided Deforestation",
        "category": ProjectCategory.AVOIDANCE,
        "country": "PE",
        "region": "Madre de Dios",
        "registry": "Verra",
        "registry_id": "VCS-1883",
        "methodology": "VM0015 Avoided Unplanned Deforestation",
        "vintage": 2023,
        "price": Decimal("1320.00"),
        "currency": "INR",
        "quantity": Decimal("88000.000"),
        "sdgs": [1, 12, 13, 15],
        "score": Decimal("83.5"),
        "risk": Decimal("23.0"),
        "confidence": Decimal("0.87"),
        "description": "Equipping 400 harvester families with satellite monitoring to stop illegal gold mining and road encroachment.",
        "image_url": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Scottish Highlands Caledonian Pine Rewilding",
        "developer": "Caledonia Rewilding Trust",
        "type": "Reforestation",
        "category": ProjectCategory.REMOVAL,
        "country": "UK",
        "region": "Highlands",
        "registry": "Verra",
        "registry_id": "VCS-3391",
        "methodology": "AR-ACM0003 Woodland Creation",
        "vintage": 2024,
        "price": Decimal("2600.00"),
        "currency": "INR",
        "quantity": Decimal("22000.000"),
        "sdgs": [13, 15],
        "score": Decimal("91.5"),
        "risk": Decimal("10.0"),
        "confidence": Decimal("0.95"),
        "description": "Regenerating ancient Scots pine and birch forest corridors with natural regeneration deer exclosures.",
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Himachal Apple Orchards Regenerative Biochar",
        "developer": "Himalayan Soil Health Society",
        "type": "Biochar & Agroforestry",
        "category": ProjectCategory.REMOVAL,
        "country": "IN",
        "region": "Himachal Pradesh",
        "registry": "Gold Standard",
        "registry_id": "GS-7450",
        "methodology": "GS TPD Agroforestry & Pyrogenic Carbon",
        "vintage": 2024,
        "price": Decimal("1690.00"),
        "currency": "INR",
        "quantity": Decimal("39000.000"),
        "sdgs": [2, 12, 13, 15],
        "score": Decimal("89.0"),
        "risk": Decimal("13.0"),
        "confidence": Decimal("0.92"),
        "description": "Converting seasonal pruning waste into biochar applied with mycorrhizal fungi to mountain orchard soils.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Ghana Ashanti Cocoa Agroforestry Transition",
        "developer": "Ashanti Farmer Carbon Syndicate",
        "type": "Biochar & Agroforestry",
        "category": ProjectCategory.REMOVAL,
        "country": "GH",
        "region": "Ashanti",
        "registry": "Gold Standard",
        "registry_id": "GS-5620",
        "methodology": "GS Agroforestry Standards",
        "vintage": 2024,
        "price": Decimal("1450.00"),
        "currency": "INR",
        "quantity": Decimal("57000.000"),
        "sdgs": [1, 2, 8, 13, 15],
        "score": Decimal("87.0"),
        "risk": Decimal("16.0"),
        "confidence": Decimal("0.90"),
        "description": "Transforming sun-cocoa plantations into biodiverse shade systems with nitrogen-fixing leguminous trees.",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Yucatan Peninsula Mangrove Biosphere",
        "developer": "Reserva Celestún Conservación AC",
        "type": "Mangrove Restoration",
        "category": ProjectCategory.REMOVAL,
        "country": "MX",
        "region": "Yucatan",
        "registry": "Verra",
        "registry_id": "VCS-2915",
        "methodology": "VM0033 Tidal Wetland Restoration",
        "vintage": 2024,
        "price": Decimal("1580.00"),
        "currency": "INR",
        "quantity": Decimal("49000.000"),
        "sdgs": [13, 14, 15],
        "score": Decimal("88.0"),
        "risk": Decimal("15.0"),
        "confidence": Decimal("0.91"),
        "description": "Desilting hypersaline tidal channels to restore natural flushing and promote red mangrove regeneration.",
        "image_url": "https://images.unsplash.com/photo-1718661934073-ecfd78710651?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
    {
        "name": "Appalachian Post-Mining Land Reforestation",
        "developer": "Green Forests Work Cooperative",
        "type": "Improved Forest Management",
        "category": ProjectCategory.REMOVAL,
        "country": "US",
        "region": "Kentucky",
        "registry": "American Carbon Registry",
        "registry_id": "ACR-699",
        "methodology": "ACR IFM Non-Federal US Forests",
        "vintage": 2024,
        "price": Decimal("2450.00"),
        "currency": "INR",
        "quantity": Decimal("33000.000"),
        "sdgs": [8, 13, 15],
        "score": Decimal("90.0"),
        "risk": Decimal("11.0"),
        "confidence": Decimal("0.94"),
        "description": "Deep-ripping compacted strip mine benches to plant high-biomass American chestnut and native hardwoods.",
        "image_url": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=srgb&fm=jpg&w=900",
    },
]

def seed() -> None:
    session = SessionLocal()
    try:
        inserted = 0
        print(f"Checking {len(PROJECT_DATA)} projects for database seed...")
        for data in PROJECT_DATA:
            existing = session.query(Project).filter_by(registry_project_id=data["registry_id"]).first()
            if existing:
                continue
            inserted += 1
            proj_id = uuid4()
            slug = data["name"].lower().replace(" ", "-").replace("&", "and")
            project = Project(
                id=proj_id,
                external_id=f"EXT-{data['registry_id']}",
                name=data["name"],
                slug=slug,
                developer_name=data["developer"],
                description=data["description"],
                country_code=data["country"],
                region=data["region"],
                project_type=data["type"],
                category=data["category"],
                registry=data["registry"],
                registry_project_id=data["registry_id"],
                methodology=data["methodology"],
                vintage_start=data["vintage"],
                vintage_end=data["vintage"],
                verification_status=VerificationStatus.VERIFIED,
                status=ProjectStatus.ACTIVE,
                price_per_credit=data["price"],
                currency=data["currency"],
                available_quantity=data["quantity"],
                sdgs=data["sdgs"],
                source_url=f"https://registry.example.com/project/{data['registry_id']}",
                data_as_of=date.today(),
                is_synthetic=False,
            )
            session.add(project)

            # Carbon credit inventory
            credit = CarbonCredit(
                id=uuid4(),
                project_id=proj_id,
                vintage=data["vintage"],
                quantity_available=data["quantity"],
                price_per_credit=data["price"],
                currency=data["currency"],
                data_as_of=date.today(),
            )
            session.add(credit)

            # Score across 7 dimensions
            score = ProjectScore(
                id=uuid4(),
                project_id=proj_id,
                integrity_score=data["score"],
                permanence_score=data["score"],
                verification_score=data["score"] + Decimal("2"),
                co_benefits_score=data["score"] - Decimal("3"),
                value_score=Decimal("80.0"),
                delivery_score=Decimal("85.0"),
                compatibility_score=Decimal("82.0"),
                quality_score=data["score"],
                impact_score=data["score"],
                risk_score=data["risk"],
                carboniq_score=data["score"],
                confidence=data["confidence"],
                explanation={"notes": "Audited third-party verification standard.", "missing_evidence": []},
                methodology_version="1.0.0",
                calculated_at=datetime.now(timezone.utc),
            )
            session.add(score)

            # Add low/info risk signal
            risk_signal = RiskSignal(
                id=uuid4(),
                project_id=proj_id,
                code="RSK-MONITORING-SCHEDULE",
                severity=RiskSeverity.LOW if data["risk"] < 20 else RiskSeverity.MEDIUM,
                title="Scheduled Verification Audit Approaching",
                message=f"Next periodic monitoring verification report for {data['name']} scheduled for Q4 2026.",
                evidence={"registry_id": data["registry_id"]},
                requires_review=False,
                rule_version="1.0.0",
                detected_at=datetime.now(timezone.utc),
            )
            session.add(risk_signal)

        session.commit()
        print("Database seeded successfully!")
    finally:
        session.close()

if __name__ == "__main__":
    seed()
